-- Database: pruebaTecnica

-- DROP DATABASE "pruebaTecnica";

CREATE DATABASE "pruebaTecnica"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.utf8'
    LC_CTYPE = 'Spanish_Spain.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
    
    - Table: public.clientes

-- DROP TABLE public.clientes;

CREATE TABLE public.clientes
(
    id_cliente bigint NOT NULL DEFAULT nextval('clientes_id_cliente_seq'::regclass),
    direccion_per character varying(255) COLLATE pg_catalog."default",
    edad_per integer,
    genero_per character(1) COLLATE pg_catalog."default",
    identificacion_per character varying(255) COLLATE pg_catalog."default",
    nompre_per character varying(255) COLLATE pg_catalog."default",
    telefono_per character varying(255) COLLATE pg_catalog."default",
    contrasenia character varying(255) COLLATE pg_catalog."default",
    estado boolean,
    idcliente bigint NOT NULL,
    CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.clientes
    OWNER to postgres;
    
    
    -- Table: public.cuenta

-- DROP TABLE public.cuenta;

CREATE TABLE public.cuenta
(
    idcuenta bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    num_cuenta character varying(255) COLLATE pg_catalog."default",
    tipocuenta character varying(255) COLLATE pg_catalog."default",
    saldoinicial double precision,
    estado boolean,
    CONSTRAINT pk_cuenta PRIMARY KEY (idcuenta)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.cuenta
    OWNER to postgres;
    
    -- Table: public.movimiento

-- DROP TABLE public.movimiento;

CREATE TABLE public.movimiento
(
    idmovimiento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fechamovimiento date,
    tipo_movimiento character varying(255) COLLATE pg_catalog."default",
    valor double precision,
    total double precision,
    CONSTRAINT pk_movimiento PRIMARY KEY (idmovimiento)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.movimiento
    OWNER to postgres;